#line 2 "scanner.cpp"

#line 4 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 73
#define YY_END_OF_BUFFER 74
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[251] =
    {   0,
        0,    0,   74,   72,   69,   73,   69,   70,   72,   72,
        1,    1,    1,   71,   64,   63,   64,   64,   58,   64,
       56,   60,   57,   59,   64,   64,   64,   64,    0,    0,
       70,   70,    3,    0,    0,   42,    0,    0,    0,    0,
        0,   43,    0,    0,    1,   66,   66,   66,   64,   64,
       53,   64,   64,   64,   36,   64,   64,   64,   64,   64,
       54,   64,   64,   64,   64,   64,   64,   37,   64,   64,
       64,   11,   64,   64,   55,    0,    0,    0,    0,   65,
        0,    0,    0,    0,    0,   50,   49,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    2,   66,    9,   10,

       64,    0,   31,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,    7,   64,   64,   64,   64,   64,
       64,   32,   34,    6,   64,   64,   64,   64,   64,    0,
        0,    3,   48,    0,    0,    0,   14,    0,    0,   15,
        0,    0,    0,    0,   64,   64,   64,    8,   33,    5,
       61,   64,   38,   62,   64,   64,   64,   64,   22,   64,
       64,   64,   64,   64,   64,   64,    4,   64,    0,    0,
        0,    0,   46,   44,   41,   45,    0,    0,    0,    0,
        0,   40,   29,   39,   19,   23,   64,   35,   64,   64,
       25,   27,   20,   16,   64,   26,   28,   64,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       24,   17,   30,   18,   64,    0,    0,    0,    0,    0,
       47,    0,   51,    0,    0,    0,    0,    0,   21,    0,
       52,    0,    0,    0,    0,   67,   67,    0,   13,   12,
        0,   68,    0,   51,    0,    0,    0,    0,   51,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,    9,   10,   11,   11,   12,
       13,   11,   11,   11,   11,   11,   11,    1,    1,    1,
       14,    1,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
        1,    1,    1,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       57,   58,   31,   59,   60,   61,   62,   63,   64,   65,
       66,   67,    1,   41,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[68] =
    {   0,
        1,    1,    2,    2,    3,    4,    1,    1,    5,    6,
        7,    7,    7,    1,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        2,    1,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8
    } ;

static const flex_int16_t yy_base[268] =
    {   0,
        0,    0,  196, 1088, 1088, 1088,  184,  184,   57,    0,
       70,   84,  111, 1088,   98,  114,  124,  117,  132,  187,
      136,  144,  239,  168,  176,  203,  164,  173,  153,  231,
      165, 1088,  215,   53,   54,   56,   56,   63,  175,   61,
       55,  100,  246,  140,  254,    0,  180,  201,  258,  261,
      265,  268,  273,  276,  282,  287,  300,  303,  306,  317,
      324,  330,  333,  341,  344,  393,  358,  352,  361,  371,
      389,  366,  404,  419,  432,  447,  457,  466,  475, 1088,
      478,  487,  436,   68,  178, 1088, 1088,  190,  248,  244,
      281,  274,  329,    0,  453,  484,  490, 1088, 1088, 1088,

      493,  491,  497,  500,  504,  507,  511,  514,  517,  526,
      534,  538,  542,  566,  561,  569,  586,  589,  592,  599,
      602,  595,  617,  620,  627,  631,  641,  645,  648,  659,
      674,  654, 1088,  348,  361,  369, 1088,  375,  378, 1088,
      682,  686,  386,  426,  691,  695,  699,  703,  706,  711,
      717,  720,  723,  726,  731,  735,  739,  749,  745,  752,
      755,  766,  772,  781,  793,  796,  800,  805,  802,  833,
      859,  341, 1088, 1088, 1088, 1088,  855,  865,  871,  512,
      528,  818,  845,  878,  881,  884,  887,  891,  897,  905,
      914,  917,  920,  923,  926,  929,  932,  942,  540,  528,

      570,  573,  626,  799,  617,  707,  709,  947,  757,  803,
      950,  953,  956,  960,  963,  510,  165,  804,  813,  590,
     1088,  736, 1088,  816,  839,  804,  861,  900,  969,  924,
     1088,  155,  136,  955,  958, 1088, 1088,  961, 1088, 1088,
      132, 1088,  955, 1088,  956,  805,  954,  101, 1088, 1088,
     1019, 1027,   90, 1031, 1033, 1039, 1045, 1048,   80, 1050,
     1056, 1062,   68, 1065, 1071, 1075, 1079
    } ;

static const flex_int16_t yy_def[268] =
    {   0,
      250,    1,  250,  250,  250,  250,  251,  252,  250,  253,
      254,  254,  254,  250,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  256,  257,
      252,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  258,  250,  254,  259,  259,  259,  260,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
       66,  255,  255,  255,  255,  261,  261,  261,  262,  250,
      262,  257,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  263,  264,  258,  250,  250,  250,  250,

      260,  250,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  265,
      262,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      266,  264,  250,  250,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  250,  265,
      265,  250,  250,  250,  250,  250,  250,  267,  266,  250,
      250,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  250,  250,

      250,  250,  250,  250,  250,  250,  250,  267,  250,  250,
      255,  255,  255,  255,  255,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  255,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,    0,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250
    } ;

static const flex_int16_t yy_nxt[1156] =
    {   0,
        4,    5,    6,    5,    5,    7,    8,    9,    4,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       15,   15,   15,   15,   21,   22,   23,   15,   15,   24,
       15,   25,   26,   15,   27,   15,   28,   15,   15,   15,
        4,    4,   15,   16,   17,   18,   19,   20,   15,   15,
       15,   15,   21,   22,   23,   15,   15,   24,   25,   26,
       15,   27,   15,   28,   15,   15,   15,   33,   33,   33,
       84,   34,   85,   87,   35,  141,   36,   88,   44,   37,
       45,   45,   45,   91,   38,  133,   39,   98,   86,   40,
       41,   42,   44,   92,   45,   45,   45,   43,   84,   34,

       85,   87,   35,   47,   36,   88,  231,   37,   49,   49,
       49,   91,   38,  133,   39,   86,   40,   41,   42,   44,
       92,   45,   45,   45,   49,   49,   49,   49,   49,   49,
       48,   47,   93,   51,   49,   49,   49,  231,   53,   56,
       52,  242,   49,   49,   49,   54,   49,   49,   49,   57,
       97,   97,   97,   55,   49,   49,   49,   76,   48,   93,
      242,   51,   76,   77,   77,   77,   53,   56,   52,   58,
      231,   32,   64,   54,   49,   49,   49,   57,   49,   49,
       49,   55,   69,   49,   49,   49,   49,   49,   49,   89,
       32,   74,   75,   29,   70,  250,   58,   49,   49,   49,

       64,   59,   71,  134,   60,  250,   61,  250,  250,   62,
       69,   90,   99,   49,   49,   49,  135,   89,   72,   74,
       75,   63,   70,   83,   73,   33,   33,   33,  250,   59,
       71,  134,   60,  100,   61,   79,   80,   62,   90,   99,
      250,   81,   81,   81,  135,  250,   72,  250,   63,   49,
       49,   49,   73,  250,   65,   94,   95,   95,   95,  250,
      100,  137,   44,   66,   45,   45,   45,   67,   49,   49,
       49,   49,   49,   49,   68,   49,   49,   49,   49,   49,
       49,  136,   65,   49,   49,   49,   49,   49,   49,  137,
      250,   66,   49,   49,   49,   67,  104,   49,   49,   49,

      250,   68,  105,  139,  106,  250,  103,  250,  136,  102,
       49,   49,   49,   49,   49,   49,   49,   49,   49,  107,
      138,  109,  108,  250,  104,  250,  250,   49,   49,   49,
      105,  139,  106,  103,   49,   49,   49,  250,  110,  111,
       49,   49,   49,   49,   49,   49,  107,  138,  250,  109,
      108,   49,   49,   49,   49,   49,   49,  112,  113,  250,
      140,  114,   49,   49,   49,  110,  172,  111,   49,   49,
       49,   49,   49,   49,  203,  115,   49,   49,   49,  173,
      250,   49,   49,   49,  250,  112,  113,  140,  250,  114,
      174,  250,  120,  175,  172,  121,  176,  122,  123,  250,

      124,  203,  115,   49,   49,   49,  125,  173,   50,  126,
      116,  180,  117,  118,   49,   49,   49,  250,  174,  120,
      250,  175,  121,  127,  176,  122,  123,  119,  124,   49,
       49,   49,  128,  250,  125,  250,   50,  126,  116,  180,
      117,  118,   49,   49,   49,  129,  132,  132,  132,  250,
      127,   76,  250,  181,  119,  250,   76,   77,   77,   77,
      128,   76,   94,   95,   95,   95,   76,   77,   77,   77,
       76,  250,  250,  129,  250,   76,   77,   77,   77,   79,
       80,  181,   79,   80,  250,   81,   81,   81,   81,   81,
       81,   79,   80,   94,   95,   95,   95,   81,   81,   81,

       97,   97,   97,   49,   49,   49,  143,   49,   49,   49,
       49,   49,   49,  144,   49,   49,   49,   49,   49,   49,
      250,   49,   49,   49,   49,   49,   49,   49,   49,   49,
      250,  145,  146,  150,  143,  148,   49,   49,   49,  250,
      209,  144,  230,  147,   49,   49,   49,  149,   49,   49,
       49,  250,   49,   49,   49,  153,  210,  218,  145,  151,
      146,  150,  216,  148,  217,  250,  152,  154,  209,  230,
      147,   49,   49,   49,  149,  250,   49,   49,   49,   49,
       49,   49,  250,  153,  210,  218,  151,  219,  155,  220,
      216,  157,  217,  152,  156,  154,   49,   49,   49,   49,

       49,   49,   49,   49,   49,   49,   49,   49,  158,   49,
       49,   49,   49,   49,   49,  219,  155,  220,  159,  157,
      160,  234,  156,  161,  250,  250,  162,   49,   49,   49,
       49,   49,   49,  250,  163,  250,  158,   49,   49,   49,
      250,   49,   49,   49,  221,  159,  224,  160,  234,  164,
      161,   49,   49,   49,  162,   49,   49,   49,   49,   49,
       49,  163,  165,   76,  132,  132,  132,  169,   76,  170,
      170,  170,  221,  166,  224,  250,  168,  164,   79,   80,
      250,  167,  250,  250,   81,   81,   81,  250,  250,  165,
      177,   94,  178,  178,  178,   94,   95,   95,   95,  250,

      166,   49,   49,   49,  168,   49,   49,   49,  167,   49,
       49,   49,  183,   49,   49,   49,   49,   49,   49,  250,
      182,   49,   49,   49,  225,  226,  184,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,  250,
      183,   49,   49,   49,  185,   49,   49,   49,  182,   49,
       49,   49,  225,  226,  184,   49,   49,   49,  186,   49,
       49,   49,   49,   49,   49,   49,   49,   49,  235,  187,
      188,  189,  185,  227,  190,  250,   49,   49,   49,  250,
      250,  191,   49,   49,   49,  250,  186,  192,  250,  250,
      194,   49,   49,   49,  250,  235,  187,  188,  189,  193,

      250,  227,  190,   49,   49,   49,   49,   49,   49,  191,
       49,   49,   49,  195,  192,   49,   49,   49,  194,  199,
      228,  222,  196,  223,  232,  200,  193,  197,   49,   49,
       49,  201,  233,  250,  202,  238,  236,   76,  248,  198,
      195,  169,   76,  170,  170,  170,  250,  199,  228,  222,
      196,  223,  232,  200,  197,   49,   49,   49,  237,  201,
      233,  202,  238,   76,  236,  248,  198,  169,   76,  170,
      170,  170,  204,  177,   94,  178,  178,  178,  205,  177,
       94,  178,  178,  178,  206,  239,  237,  207,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,

      204,   49,   49,   49,  250,  250,  205,   49,   49,   49,
      250,  250,  206,  239,  207,   49,   49,   49,  240,  250,
      211,  212,  250,  213,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,  250,  240,  211,  241,  212,
      214,  213,   49,   49,   49,  177,   94,  178,  178,  178,
       49,   49,   49,   49,   49,   49,   49,   49,   49,  215,
       49,   49,   49,   49,   49,   49,  241,  243,  214,   49,
       49,   49,  244,  245,  246,  247,  250,  249,  250,  250,
      250,  250,  250,  250,  250,  250,  229,  215,  250,  250,

      250,  250,  250,  250,  250,  243,  250,  250,  250,  250,
      244,  245,  246,  247,  249,  250,  250,  250,  250,  250,
      250,  250,  250,  229,   30,  250,   30,   31,  250,   31,
       31,   31,   31,   31,   31,   46,  250,   46,   46,   50,
       50,   78,  250,  250,   78,   78,   78,   82,   82,  250,
      250,   82,   82,   96,   96,   96,  101,  101,  130,  250,
      250,  130,  130,  130,  131,  131,  250,  250,  131,  131,
      142,  142,  142,  171,  250,  171,  171,  171,  171,  179,
      179,  179,  179,  208,  208,  208,  208,    3,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,

      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250
    } ;

static const flex_int16_t yy_chk[1156] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    9,    9,    9,
       34,    9,   35,   37,    9,  263,    9,   38,   11,    9,
       11,   11,   11,   40,    9,   84,    9,  259,   36,    9,
        9,    9,   12,   41,   12,   12,   12,  253,   34,    9,

       35,   37,    9,   12,    9,   38,  248,    9,   15,   15,
       15,   40,    9,   84,    9,   36,    9,    9,    9,   13,
       41,   13,   13,   13,   16,   16,   16,   18,   18,   18,
       13,   12,   42,   16,   17,   17,   17,  241,   17,   18,
       16,  233,   19,   19,   19,   17,   21,   21,   21,   19,
       44,   44,   44,   17,   22,   22,   22,   29,   13,   42,
      232,   16,   29,   29,   29,   29,   17,   18,   16,   19,
      217,   31,   22,   17,   27,   27,   27,   19,   24,   24,
       24,   17,   24,   28,   28,   28,   25,   25,   25,   39,
        8,   27,   28,    7,   25,    3,   19,   20,   20,   20,

       22,   20,   25,   85,   20,    0,   20,    0,    0,   20,
       24,   39,   47,   26,   26,   26,   88,   39,   26,   27,
       28,   20,   25,   33,   26,   33,   33,   33,    0,   20,
       25,   85,   20,   48,   20,   30,   30,   20,   39,   47,
        0,   30,   30,   30,   88,    0,   26,    0,   20,   23,
       23,   23,   26,    0,   23,   43,   43,   43,   43,    0,
       48,   90,   45,   23,   45,   45,   45,   23,   49,   49,
       49,   50,   50,   50,   23,   51,   51,   51,   52,   52,
       52,   89,   23,   53,   53,   53,   54,   54,   54,   90,
        0,   23,   55,   55,   55,   23,   54,   56,   56,   56,

        0,   23,   54,   92,   54,    0,   53,    0,   89,   52,
       57,   57,   57,   58,   58,   58,   59,   59,   59,   56,
       91,   58,   57,    0,   54,    0,    0,   60,   60,   60,
       54,   92,   54,   53,   61,   61,   61,    0,   59,   60,
       62,   62,   62,   63,   63,   63,   56,   91,    0,   58,
       57,   64,   64,   64,   65,   65,   65,   62,   63,    0,
       93,   64,   68,   68,   68,   59,  134,   60,   67,   67,
       67,   69,   69,   69,  172,   65,   72,   72,   72,  135,
        0,   70,   70,   70,    0,   62,   63,   93,    0,   64,
      136,    0,   67,  138,  134,   69,  139,   70,   70,    0,

       70,  172,   65,   66,   66,   66,   71,  135,   71,   71,
       66,  143,   66,   66,   73,   73,   73,    0,  136,   67,
        0,  138,   69,   71,  139,   70,   70,   66,   70,   74,
       74,   74,   73,    0,   71,    0,   71,   71,   66,  143,
       66,   66,   75,   75,   75,   74,   83,   83,   83,    0,
       71,   76,    0,  144,   66,    0,   76,   76,   76,   76,
       73,   77,   95,   95,   95,   95,   77,   77,   77,   77,
       78,    0,    0,   74,    0,   78,   78,   78,   78,   79,
       79,  144,   81,   81,    0,   79,   79,   79,   81,   81,
       81,   82,   82,   96,   96,   96,   96,   82,   82,   82,

       97,   97,   97,  101,  101,  101,  102,  103,  103,  103,
      104,  104,  104,  102,  105,  105,  105,  106,  106,  106,
        0,  107,  107,  107,  108,  108,  108,  109,  109,  109,
        0,  104,  105,  109,  102,  107,  110,  110,  110,    0,
      180,  102,  216,  106,  111,  111,  111,  108,  112,  112,
      112,    0,  113,  113,  113,  112,  181,  200,  104,  110,
      105,  109,  199,  107,  199,    0,  111,  113,  180,  216,
      106,  115,  115,  115,  108,    0,  114,  114,  114,  116,
      116,  116,    0,  112,  181,  200,  110,  201,  114,  202,
      199,  116,  199,  111,  114,  113,  117,  117,  117,  118,

      118,  118,  119,  119,  119,  122,  122,  122,  117,  120,
      120,  120,  121,  121,  121,  201,  114,  202,  117,  116,
      118,  220,  114,  119,    0,    0,  120,  123,  123,  123,
      124,  124,  124,    0,  121,    0,  117,  125,  125,  125,
        0,  126,  126,  126,  203,  117,  205,  118,  220,  125,
      119,  127,  127,  127,  120,  128,  128,  128,  129,  129,
      129,  121,  126,  130,  132,  132,  132,  130,  130,  130,
      130,  130,  203,  127,  205,    0,  129,  125,  131,  131,
        0,  128,    0,    0,  131,  131,  131,    0,    0,  126,
      141,  141,  141,  141,  141,  142,  142,  142,  142,    0,

      127,  145,  145,  145,  129,  146,  146,  146,  128,  147,
      147,  147,  146,  148,  148,  148,  149,  149,  149,    0,
      145,  150,  150,  150,  206,  207,  147,  151,  151,  151,
      152,  152,  152,  153,  153,  153,  154,  154,  154,    0,
      146,  155,  155,  155,  152,  156,  156,  156,  145,  157,
      157,  157,  206,  207,  147,  159,  159,  159,  155,  158,
      158,  158,  160,  160,  160,  161,  161,  161,  222,  156,
      157,  157,  152,  209,  158,    0,  162,  162,  162,    0,
        0,  160,  163,  163,  163,    0,  155,  161,    0,    0,
      163,  164,  164,  164,    0,  222,  156,  157,  157,  162,

        0,  209,  158,  165,  165,  165,  166,  166,  166,  160,
      167,  167,  167,  164,  161,  168,  168,  168,  163,  169,
      210,  204,  165,  204,  218,  169,  162,  166,  182,  182,
      182,  169,  219,    0,  169,  226,  224,  170,  246,  168,
      164,  170,  170,  170,  170,  170,    0,  169,  210,  204,
      165,  204,  218,  169,  166,  183,  183,  183,  225,  169,
      219,  169,  226,  171,  224,  246,  168,  171,  171,  171,
      171,  171,  177,  178,  178,  178,  178,  178,  177,  179,
      179,  179,  179,  179,  177,  227,  225,  177,  184,  184,
      184,  185,  185,  185,  186,  186,  186,  187,  187,  187,

      177,  188,  188,  188,    0,    0,  177,  189,  189,  189,
        0,    0,  177,  227,  177,  190,  190,  190,  228,    0,
      187,  189,    0,  190,  191,  191,  191,  192,  192,  192,
      193,  193,  193,  194,  194,  194,  195,  195,  195,  196,
      196,  196,  197,  197,  197,    0,  228,  187,  230,  189,
      195,  190,  198,  198,  198,  208,  208,  208,  208,  208,
      211,  211,  211,  212,  212,  212,  213,  213,  213,  198,
      214,  214,  214,  215,  215,  215,  230,  234,  195,  229,
      229,  229,  235,  238,  243,  245,    0,  247,    0,    0,
        0,    0,    0,    0,    0,    0,  215,  198,    0,    0,

        0,    0,    0,    0,    0,  234,    0,    0,    0,    0,
      235,  238,  243,  245,  247,    0,    0,    0,    0,    0,
        0,    0,    0,  215,  251,    0,  251,  252,    0,  252,
      252,  252,  252,  252,  252,  254,    0,  254,  254,  255,
      255,  256,    0,    0,  256,  256,  256,  257,  257,    0,
        0,  257,  257,  258,  258,  258,  260,  260,  261,    0,
        0,  261,  261,  261,  262,  262,    0,    0,  262,  262,
      264,  264,  264,  265,    0,  265,  265,  265,  265,  266,
      266,  266,  266,  267,  267,  267,  267,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,

      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "flex.l"
#line 2 "flex.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <iostream>
#include "parser.h"

using namespace std;

#line 794 "scanner.cpp"
/*----------------------------------------------------- SECCION DE DEFINICIONES----------------------------------- */
/* NUMEROS  */
/* ADMINISTRADOR DE DISCOS*/
/* GESTOR DE USUARIOS Y GRUPOS*/
/*ADMIND DE PERSIMOS Y ARCHIVOS*/
/*  PARAMETROS  */
/* ENTRADAS */
/* OTROS */
/* IDES  para discos*/
/*----------------------------------------------------- SECCION DE REGLAS -------------------------------------*/
#line 805 "scanner.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 106 "flex.l"


#line 1025 "scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 251 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1088 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 108 "flex.l"
{yylval.number = atoi(yytext); return(number);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 109 "flex.l"
{yylval.number = atoi(yytext); return(number);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 110 "flex.l"
{yylval.number = atoi(yytext); return(number);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 112 "flex.l"
{return(show);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 113 "flex.l"
{return(readfile);}
	YY_BREAK
/*REPORTES*/
case 6:
YY_RULE_SETUP
#line 116 "flex.l"
{strcpy(yylval.text, yytext); return(rep);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 117 "flex.l"
{strcpy(yylval.text, yytext); return(r_mbr);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 118 "flex.l"
{strcpy(yylval.text, yytext); return(r_disk);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 119 "flex.l"
{strcpy(yylval.text, yytext); return(fs_option);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 120 "flex.l"
{strcpy(yylval.text, yytext); return(fs_option);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 121 "flex.l"
{strcpy(yylval.text, yytext); return(sb);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 122 "flex.l"
{strcpy(yylval.text, yytext); return(bm_inode);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 123 "flex.l"
{strcpy(yylval.text, yytext); return(bm_block);}
	YY_BREAK
/*---------- para login */
case 14:
YY_RULE_SETUP
#line 125 "flex.l"
{strcpy(yylval.text, yytext); return(p_pass);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 126 "flex.l"
{strcpy(yylval.text, yytext); return(p_ussr);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 128 "flex.l"
{return(pausado);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 129 "flex.l"
{return(mkdisk);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 130 "flex.l"
{return(rmdisk);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 131 "flex.l"
{return(fdisk);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 132 "flex.l"
{return(mount);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 133 "flex.l"
{return(unmount);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 134 "flex.l"
{return(mkfs);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 136 "flex.l"
{return(login);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 137 "flex.l"
{return(logout);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 138 "flex.l"
{printf("Funcion mkgrp %s ", yytext);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 139 "flex.l"
{printf("Funcion rmgrp %s ", yytext);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 140 "flex.l"
{printf("Funcion mkurs %s ", yytext);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 141 "flex.l"
{printf("Funcion rmusr %s ", yytext);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 143 "flex.l"
{printf("Funcion chmod %s ", yytext);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 144 "flex.l"
{printf("Funcion mkfile %s ", yytext);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 145 "flex.l"
{printf("Funcion cat %s ", yytext);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 146 "flex.l"
{printf("Funcion rem %s ", yytext);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 147 "flex.l"
{printf("Funcion edit %s ", yytext);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 148 "flex.l"
{printf("Funcion ren %s ", yytext);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 149 "flex.l"
{printf("Funcion mkdir %s ", yytext);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 150 "flex.l"
{printf("Funcion cp %s ", yytext);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 151 "flex.l"
{printf("Funcion mv %s ", yytext);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 152 "flex.l"
{printf("Funcion find %s", yytext);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 153 "flex.l"
{printf("Funcion chown %s", yytext);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 154 "flex.l"
{printf("Funcion chgrp %s", yytext);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 156 "flex.l"
{return(size);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 157 "flex.l"
{return(fit);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 158 "flex.l"
{return(units);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 159 "flex.l"
{return(path);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 160 "flex.l"
{return(type);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 161 "flex.l"
{return(name);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 162 "flex.l"
{return(dele);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 163 "flex.l"
{return(add);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 164 "flex.l"
{return(id);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 165 "flex.l"
{return(fs);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 168 "flex.l"
{strcpy(yylval.text, yytext); return(e_path);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 169 "flex.l"
{strcpy(yylval.text, yytext); return(e_path);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 170 "flex.l"
{sscanf(yytext, "%s", yylval.entrace); return(e_fit);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 171 "flex.l"
{sscanf(yytext, "%s", yylval.entrace); return(e_fit);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 172 "flex.l"
{sscanf(yytext, "%s", yylval.entrace); return(e_fit);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 173 "flex.l"
{sscanf(yytext, "%s", yylval.entrace); return(e_units);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 174 "flex.l"
{sscanf(yytext, "%s", yylval.entrace); return(e_units);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 175 "flex.l"
{sscanf(yytext, "%s", yylval.entrace); return(e_type);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 176 "flex.l"
{sscanf(yytext, "%s", yylval.entrace); return(e_type);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 177 "flex.l"
{sscanf(yytext, "%s", yylval.entrace); return(e_type);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 178 "flex.l"
{sscanf(yytext, "%s", yylval.entrace); return(e_delete);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 179 "flex.l"
{sscanf(yytext, "%s", yylval.entrace); return(e_delete);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 180 "flex.l"
{sscanf(yytext, "%s", yylval.entrace); return(e_units);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 181 "flex.l"
{strcpy(yylval.text, yytext); return(e_name);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 182 "flex.l"
{strcpy(yylval.text, yytext); return(e_name);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 183 "flex.l"
{strcpy(yylval.text, yytext); return(e_id);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 185 "flex.l"
{strcpy(yylval.text, yytext); return(e_pdf_path);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 186 "flex.l"
{strcpy(yylval.text, yytext); return(e_pdf_path);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 189 "flex.l"
{}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 190 "flex.l"
{strcpy(yylval.text, yytext); return(comentario);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 191 "flex.l"
{return(igual);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 192 "flex.l"
{printf("Caracter %s no admitido\n ", yytext);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 195 "flex.l"
ECHO;
	YY_BREAK
#line 1449 "scanner.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 251 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 251 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 250);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 195 "flex.l"

